
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'YunDi_Student' do

pod 'AFNetworking', '~> 3.0'
pod 'FMDB'
pod 'MJRefresh'
pod 'MJExtension'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'TPKeyboardAvoiding', '1.2.4'
pod 'SDWebImage', '~>3.8'
pod 'Masonry'
pod 'TTTAttributedLabel'

pod 'BlocksKit', '2.2.5'
pod "QBImagePickerController"

end
